name:                blog-example-hlint
version:             0.1.0.0
github:              "waddlaw/blog-example-hlint"
license:             BSD3
author:              "shinya yamaguchi"
maintainer:          "ingroze@gmail.com"
copyright:           "Copyright (c) 2017 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Your Projects Category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/waddlaw/blog-example-hlint#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  blog-example-hlint-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-example-hlint

tests:
  blog-example-hlint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-example-hlint
